#!/bin/sh
# Simple utility to install or update jira_import in your local bin directory.
#
# DEPRECATED in v2.0 - just download latest version from
# https://github.com/ggruen/jira_import/releases/latest, no "git clone" or
# "cpanm JIRA::REST" required.
#
# Keeping this script for backwards compatibility or to use if you're doing
# development and want to install the lightweight version of the script because
# you already have JIRA::REST installed.
#
# usage:
#    # Only needed if you haven't cloned the repo
#    git clone https://ggruen@github.com/ggruen/jira_import.git
#    cd jira_import
#    ./install
#
# or, if you already cloned the repo:
# /path_to_repo/install
#
# `install` does a git pull on the repo, then copies jira_import to ~/bin,
# if ~/bin exists.
#
# You can run this script any time you like to keep jira_import updated.
# e.g. you could add this to crontab (assuming "git pull" is set up to not
# require a password):
# # Check for jira_import updates Sunday at midnight
# 0 0 * * 0 /path_to_repo/install

# Fail on any non-zero exit status
set -e

BASEDIR=`dirname "$0"`
cd "$BASEDIR" # Script exits if this fails due to "set -e" above

git pull && cp ./jira_import.pl "$HOME/bin/jira_import" \
    && chmod 555 "$HOME/bin/jira_import"

echo "Installed jira_import in $HOME/bin"
